server:
  port: 8080

## Spring MVC actuator endpoints available via /admin/info, /admin/health, ...
#server.servlet-path: /
#management:
#  context-path: /admin
#  security:
#    enabled: false
#
#endpoints:
#  enabled: false
#  info:
#    enabled: true
#  health:
#    enabled: true
#  beans:
#    enabled: true
#
#togglz:
##  enabled: true # Enabled by default
##  featureEnums:
##    com.citiustech.config.FeatureToggles
#  features:
#    TEXT_BASED_SEARCH_VIA_ELASTIC_SEARCH:
#      enabled: true
#    CONTENT_RETRIEVAL_VIA_CMS:
#      enabled: false
#    USE_NEW_SOMESERVICE:
#      enabled: true
#


togglz:
  console:
    enabled: true # Enable admin console.
    path: /togglz-console # The path of the admin console when enabled.
  features:
    FOO:
      enabled: true
    BAR:
      enabled: false