server:
  port: 8080

logging:
  level:
    org.togglz: DEBUG

togglz:
  features:
    DEFAULT_SERVICE1:
      enabled: true
    DEFAULT_SERVICE2:
      enabled: false
    SERVICE_A:
      enabled: true
    SERVICE_F:
      enabled: true
    SERVICE_B:
      enabled: true
    SERVICE_C:
      enabled: false
    SERVICE_D:
      enabled: true
    SERVICE_E:
      enabled: true
  
  console:
    secured: false
    enabled: true
    path: /togglz-console
